### ISSUE TITLE
udev rules

### ISSUE THREAD

**Issue by expipiplus1** [adamgreig/ecpdap#13]
It would be great to have a sample udev rule file in the repo, something like:

```
# CMSIS-DAP probe
SUBSYSTEM=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="602b", MODE="0666"
```

**Comment by adamgreig** [comment]
Thanks, good idea. I've added a slightly different version of a rules file in a290fc9, which allows any probe with "CMSIS-DAP" in the product name, rather than a specific vendor and product ID; this usually works OK for me but let me know if there's any issues!

**Comment by expipiplus1** [comment]
Thanks!
