### ISSUE TITLE
'ecpdap probes' or 'scan' crashes on Windows with latest Rust

### ISSUE THREAD

**Issue by SiliconWizard** [adamgreig/ecpdap#16]
Using Rust 1.58.0, I rebuilt ecpdap 0.1.7 lately for Windows (x64).
It now crashes and while I'm not sure exactly the cause, it seems to be crashing in libusb. I tried building it using 3 differents ways:
- MSYS2 on Windows using GCC rather than MSVC
- Direct Rust install on Windows using MSVC
- As a cross compilation on Linux using the target x86_64-pc-windows-gnu

But in those 3 cases, the versions were the same:

Rust 1.58.0
libusb1-sys v0.4.4

**Comment by adamgreig** [comment]
Hm, that's annoying, thanks for reporting. Any information on the crash or error messages? What if you run with `RUST_BACKTRACE=1` set? I don't have any experience debugging crashes in Windows unfortunately.

Could you also try with an older rust (`rustup install 1.52`, `cargo +1.52 run --release` etc) to see if it is a rust-related issue?

**Comment by SiliconWizard** [comment]
Using RUST_BACKTRACE=1, it doesn't display anything more. An 'ecpdap probe' just hangs for a few seconds, then crashes.
The MSYS2 build, which builds against a shared version of libusb (DLL), allowed me to see that the crash was a segmentation fault somewhere in libusb.

I had built v0.1.7 on Windows successfully with earlier versions of Rust (and possibly libusb1-sys), unfortunately I'm not sure anymore what the last "good" versions were... :(

Just tried what you suggested (forcing Rust 1.52), and the result is the same. :(
But the version of libusb1-sys it uses is still v0.4.4 - can you tell me how I can force it to use an older version of it so we can see if it's the culprit?

**Comment by adamgreig** [comment]
How about with `RUST_LOG=trace` to hopefully see where it gets to before crashing?

There have been a few new releases of rusb recently, which is the high level wrapper ecpdap uses (via jtagdap) to interact with libusb1-sys. It might be worth trying to update to the newest version instead of downgrading.

If you clone [jtagdap](https://github.com/adamgreig/jtagdap), modify `Cargo.toml` to use `rusb` version 0.9.0, then modify ecpdap's `Cargo.toml` to use your local clone of jtagdap (put `jtagdap = { path = "../jtagdap" }` instead of `jtagdap = 0.1.0`), then use `cargo tree` to check it's pulling in rusb 0.9 and libusb1-sys 0.6, and see if that helps?

**Comment by SiliconWizard** [comment]
Thanks. This is what I get before it crashes:

> 2022-01-19T00:24:26.442Z DEBUG jtagdap::probe > Attempting to open any connected probe
> 2022-01-19T00:24:26.442Z TRACE jtagdap::probe > Searching for CMSIS-DAP probes

Digging a bit, libusb1-sys seems to just be a thin layer above libusb, so there is relatively little chance it's really the problem... but looking at the libusb project, we may have a cause:

https://github.com/libusb/libusb/issues/844

That would be an issue with the latest libusb 1.0.24... which is indeed the one that is used in my case, both with GCC and MSVC.

**Comment by adamgreig** [comment]
Can you download some older libusb DLLs? I _think_ if they're in the same directory as the ecpdap exe it should pick them up, but I'm not sure how the libusb1-sys version interacts with that. If it's dying just searching for devices you'd think this would have been more widely noticed, though, so it might still be worth trying with newer libusb1-sys and rusb crates.

**Comment by SiliconWizard** [comment]
Got ahold of the DLL for libusb 1.0.23 (from official releases: https://github.com/libusb/libusb/releases ), rebuilt ecpdap using latest Rust and GCC (using MSVC, it builds with a static version of libusb). So I can confirm that with libusb 1.0.23, **it works fine**.

Example:

>  2022-01-19T01:27:37.580Z TRACE jtagdap::probe > Searching for CMSIS-DAP probes
>  2022-01-19T01:27:40.342Z TRACE jtagdap::probe > Found 0 devices using rusb, searching HID
>  2022-01-19T01:27:40.359Z TRACE jtagdap::probe > Adding new HID-only probe 0d28:0204:1101360250313120303739303030343139313039
> 97969903 DAPLink CMSIS-DAP
>  2022-01-19T01:27:40.359Z TRACE jtagdap::probe > Found 1 probes in total
> Found 1 CMSIS-DAP probe:
>   0d28:0204:110136025031312030373930303034313931303997969903 DAPLink CMSIS-DAP

The problem is definitely the one I mentioned above (I saw mentions of libusb accessing the libusbK driver before the access violation, using GDB, with libusb 1.0.24.) The problem is strictly on Windows and strictly if you have a libusbK driver installed, which is a combination that not everyone will have.

They fixed the bug in libusb and the fix should be in v. 1.0.25 (along with a number of other fixes). Hopefully it gets released soon, it's been due for a few months already... ;) )

**Comment by adamgreig** [comment]
Great, thanks for investigating! I guess I'll just sit tight and wait for libusb 1.0.25, then.

**Comment by adamgreig** [comment]
It looks like libusb 1.0.25 has been released now (https://github.com/libusb/libusb/releases/tag/v1.0.25), any chance you could double check that version fixes the issue? I guess this issue can be closed if so.

**Comment by SiliconWizard** [comment]
Yes, I just tried with the libusb 1.0.25 release, and it fixes the issue, as expected. :)

**Comment by adamgreig** [comment]
Thank you for checking!
