### ISSUE TITLE
`ecpdap scan` gets ERROR jtagdap::jtag > JTAG DR scan chain is empty

### ISSUE THREAD

**Issue by hotteshen** [adamgreig/ecpdap#17]
Connected a newly bought Colorlight i5 Lattice ECP5 module and carrier board.
I was following the [getting started tutorial](https://tomverbeure.github.io/2021/01/22/The-Colorlight-i5-as-FPGA-development-board.html#from-unboxing-to-blinky).
It has an onboard debugger.
And I got this error.

```
$ ecpdap scan
 2022-02-04T17:15:47.959Z ERROR jtagdap::jtag > JTAG DR scan chain is empty
Error: JTAG scan chain broken: check connection or try a larger --scan-chain-length.
```

**Comment by adamgreig** [comment]
I think that board uses spring-loaded pins to connect the debugger to the i5 module; could you double check those are all making a good connection and the FPGA is powered up?

This error basically means "ecpdap could talk to the debugger fine, and the debugger successfully ran a search on the JTAG bus, but no devices responded" - so the most likely issue is that either the connection is bad or the FPGA isn't powered for some reason.

You could also set `RUST_LOG=trace` to get more debug information, but my guess is it won't be very revealing for this error.

**Comment by hotteshen** [comment]
I have two kits and the FPGAs are powered.
But same errors on both boards.
I'll check the connections in more detail.

**Comment by SiliconWizard** [comment]
I'll second what Adam said. Having one of those boards, I can confirm that the spring-loaded pins tend not to make good connection. You can quickly try by pushing on the i5 module in the JTAG connector area while attempting to scan. It should work.

Then just remove the module from the base board, and clean the pins and the through-holes on the i5 module with some alcohol, and put it back in. That solved the finicky JTAG behavior for me.

**Comment by hotteshen** [comment]
Yes, it worked.
It was JTAG pin header issue, certainly.
Thank you, Adam and Silicon.
